from enum import Enum


class WsDataCollection(str, Enum):
    ANALYSISSETTINGS = "analysisSettings"
    ARTICLECATALOG = "articleCatalog"
    ARTICLECATALOGITEMREMOVED = "articleCatalog:itemRemoved"
    ARTICLECATALOGITEMUPDATED = "articleCatalog:itemUpdated"
    BLOCKSETTINGS = "blockSettings"
    CATALOGTORECEIPTNAMEMAPPING = "catalogToReceiptNameMapping"
    CATALOGTORECEIPTNAMEMAPPINGITEMREMOVED = "catalogToReceiptNameMapping:itemRemoved"
    CATALOGTORECEIPTNAMEMAPPINGITEMUPDATED = "catalogToReceiptNameMapping:itemUpdated"
    CATEGORIES = "categories"
    CATEGORIESITEMADDED = "categories:itemAdded"
    CATEGORIESITEMREMOVED = "categories:itemRemoved"
    CATEGORIESITEMUPDATED = "categories:itemUpdated"
    PANTRIES = "pantries"
    PANTRIESITEMREMOVED = "pantries:itemRemoved"
    PANTRIESITEMUPDATED = "pantries:itemUpdated"
    PANTRYLIST = "pantryList"
    PANTRYLISTITEMADDED = "pantryList:itemAdded"
    PANTRYLISTITEMREMOVED = "pantryList:itemRemoved"
    PANTRYLISTITEMUPDATED = "pantryList:itemUpdated"
    PURCHASESITEMADDED = "purchases:itemAdded"
    PURCHASESITEMREMOVED = "purchases:itemRemoved"
    PURCHASESITEMUPDATED = "purchases:itemUpdated"
    SHOPPINGCART = "shoppingCart"
    SHOPPINGCARTITEMADDED = "shoppingCart:itemAdded"
    SHOPPINGCARTITEMREMOVED = "shoppingCart:itemRemoved"
    SHOPPINGCARTITEMUPDATED = "shoppingCart:itemUpdated"
    SHOPPINGLIST = "shoppingList"
    SHOPPINGLISTITEMADDED = "shoppingList:itemAdded"
    SHOPPINGLISTITEMREMOVED = "shoppingList:itemRemoved"
    SHOPPINGLISTITEMUPDATED = "shoppingList:itemUpdated"
    SUPERMARKETS = "supermarkets"
    SUPERMARKETSITEMADDED = "supermarkets:itemAdded"
    SUPERMARKETSITEMREMOVED = "supermarkets:itemRemoved"
    SUPERMARKETSITEMUPDATED = "supermarkets:itemUpdated"
    UNITS = "units"
    UNITSITEMADDED = "units:itemAdded"
    UNITSITEMREMOVED = "units:itemRemoved"
    UNITSITEMUPDATED = "units:itemUpdated"
    WEEKPLAN = "weekPlan"

    def __str__(self) -> str:
        return str(self.value)
