from enum import Enum


class RecipeDtoCategoriesItem(str, Enum):
    APPETIZER = "Appetizer"
    BAKING = "Baking"
    BASIC = "Basic"
    BREAKFAST = "Breakfast"
    CASSEROLE = "Casserole"
    CLEANEATING = "CleanEating"
    DESSERT = "Dessert"
    DETOX = "Detox"
    DINNER = "Dinner"
    DOUGHDISH = "DoughDish"
    EASY = "Easy"
    FEWINGREDIENTS = "FewIngredients"
    FISH = "Fish"
    FRUITS = "Fruits"
    GLUTENFREE = "GlutenFree"
    HIGHFIBER = "HighFiber"
    HIGHPROTEIN = "HighProtein"
    KETO = "Keto"
    LACTOSEFREE = "LactoseFree"
    LOWCALORIE = "LowCalorie"
    LOWCARB = "LowCarb"
    LOWFAT = "LowFat"
    LUNCH = "Lunch"
    MEAT = "Meat"
    OVENDISH = "OvenDish"
    PASTA = "Pasta"
    PESCATARIAN = "Pescatarian"
    POTATOES = "Potatoes"
    POULTRY = "Poultry"
    QUICK = "Quick"
    RICE = "Rice"
    SALAD = "Salad"
    SHAKE = "Shake"
    SIDEDISH = "SideDish"
    SMOOTHIE = "Smoothie"
    SNACKS = "Snacks"
    SOUP = "Soup"
    STEW = "Stew"
    SUGARFREE = "SugarFree"
    SWEET = "Sweet"
    TOGO = "ToGo"
    VEGAN = "Vegan"
    VEGETABLES = "Vegetables"
    VEGETARIAN = "Vegetarian"

    def __str__(self) -> str:
        return str(self.value)
